services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8088

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8088:8088'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/AnkithaDatabase

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo-data: